# Generated by Django 3.0.5 on 2020-06-01 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_details_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 16, 41, 47, 39792)),
        ),
        migrations.AlterField(
            model_name='details',
            name='status',
            field=models.TextField(default='Available'),
        ),
    ]
