# Generated by Django 3.0.5 on 2020-06-02 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200601_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='isOnline',
            field=models.CharField(default='false', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='lastseen',
            field=models.CharField(default='not available', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 8, 58, 0, 698291)),
        ),
    ]
