# Generated by Django 3.0.6 on 2020-06-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200603_1935'),
        ('accounts', '0012_auto_20200603_2039'),
    ]

    operations = [
    ]
