# Generated by Django 3.0.6 on 2020-06-03 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20200603_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 23, 5, 3, 218950)),
        ),
    ]
