# Generated by Django 3.0.6 on 2020-06-04 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200604_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 19, 6, 10, 476158)),
        ),
    ]
