# Generated by Django 3.0.5 on 2020-06-05 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200605_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatimages',
        ),
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 19, 50, 24, 25241)),
        ),
    ]
