# Generated by Django 3.0.5 on 2020-06-08 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200606_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_DP', models.ImageField(upload_to='custom_DP/')),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 19, 6, 14, 155024)),
        ),
    ]
