# Generated by Django 3.0.6 on 2020-06-13 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200613_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='chat_order',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 11, 48, 37, 452187)),
        ),
    ]
