# Generated by Django 3.0.6 on 2020-06-13 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200613_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='chat_order',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 11, 49, 41, 819053)),
        ),
    ]
