# Generated by Django 3.0.6 on 2020-06-13 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200613_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='chat_order',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 11, 52, 3, 394443)),
        ),
    ]
