# Generated by Django 3.0.6 on 2020-06-18 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200618_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 14, 59, 15, 985324, tzinfo=utc)),
        ),
    ]
