# Generated by Django 3.0.6 on 2020-06-18 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200618_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 15, 0, 43, 283466, tzinfo=utc)),
        ),
    ]
