# Generated by Django 3.0.6 on 2020-06-18 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200618_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
